### ISSUE TITLE
Misspelling in TimeDrawImprovements.py

### ISSUE THREAD

**Issue by charlyr82** [danscully/d3script#1]
Hi,
Between lines 82 and 89 in the TimeDrawImprovements.py file there seems to be a spelling mistake END_BITMZP_SIZE which was throwing a lot of errors in disguise when loading this script.

I did a find and replace which found 9 instances of this, and replaced it with END_BITMAP_SIZE which seems to have made it work.

**Comment by danscully** [comment]
What d3 release are you using?

Between r29.0 and r30.0, the Disguise fixed their typo of that word.  Currently there is logic so that for versions r30 and higher, I use the corrected version, and for versions before r29 I use the mispelled version.  But I didn't check any r29 release after r29.1.2...

**Comment by charlyr82** [comment]
I’m running r29.2.2 so they must have fixed it slightly earlier.

**Comment by danscully** [comment]
I've updated the script with a fix, but it is untested (basically, instead of checking for a version, I check for the existence of the variable in question).  Closing this hoping it is fixed / The answer is to upgrade to r30 :)
